# 파일 위치: ./docker/default.conf (내가 수동으로 생성)

upstream apps {
    server web-green:8000; # 최초 배포 시 A팀(8001번 외부 포트와 매핑된 서비스) 조준
}

server {
    listen 80;

    location / {
        proxy_pass http://apps;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}