# 파일 위치: ./docker/default.conf (내가 수동으로 생성)

upstream apps {
    server web-blue:8000; # 최초 배포 시 A팀(8001번 외부 포트와 매핑된 서비스) 조준
}

server {
    listen 80;

    # 🌐 [핵심 추가] 도커 내부 DNS 서버 주소(127.0.0.11)를 지정하고, 1초마다 주소록을 갱신하도록 강제합니다!
    resolver 127.0.0.11 valid=1s;
    
    location / {
        set $backend_servers "apps";
        proxy_pass http://$backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}