version: '3.8'

services:
  fastapi: # service 의 이름은 마음대로 지을 수 있다.
    image: yimjongwon/lock-app:latest # 빌드된 이미지 이름 설정
    container_name: lb-fastapi
    pull_policy: always
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - lb-net

  security-nginx:
    build:
      context: ./nginx
    image: yimjongwon/lock-security-nginx:latest
    container_name: lb-security-nginx
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - lb-net
  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: lb-nginx-exporter
    command:
      - -nginx.scrape-uri=http://security-nginx/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - security-nginx
    restart: unless-stopped
    networks:
      - lb-net
    
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: lb-fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./fail2ban:/data
    environment:
      - TZ=Asia/Seoul
      - F2B_LOG_LEVEL=INFO
    depends_on:
      - security-nginx

  promtail:
    image: grafana/promtail:2.9.8
    container_name: lb-promtail
    restart: unless-stopped
    
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    command:
      - "-config.file=/etc/promtail/promtail-config.yaml"
      - "-config.expand-env=true"
    environment:
      - LOKI_HOST=${LOKI_HOST}
    networks:
      - lb-net

volumes:
  nginx_logs:
networks:
  lb-net:
    driver: bridge