# security/nginx/log-format.conf
# 보안 분석용 Access Log 형식 정의
# 공격 탐지 및 모니터링 데이터 수집 (fail2ban, Grafana, Prometheus 연계용)

# 사용 위치 : access_log /var/log/nginx/access.log security_log;
# 로그 포함 내용
# 1. 클라이언트 IP 주소 : 공격자 IP 추적 및 차단 정책에 활용
# 2. 요청 발생 시간 : 공격 시점 및 장애 발생 시점 분석
# 3. 요청 정보 : 어떤 API를 호출했는지 확인 가능.
# 4. HTTP 상태 응답 코드 : 200(정상), 401(로그인 실패),
#         429(Rate Limit 차단), 404 & 500 (서버 오류)
# 5. 응답 데이터 크기 : 비정상적으로 큰 응답 탐지 가능
# 6. 요청 처리 시간(초) : 응답 지연 및 성능 분석에 활용
# 7. 실제 사용자 IP : fail2ban 및 보안 로그 분석에 중요
# 8. 사용자 브라우저 또는 요청 도구 정보 : 정상/자동화 공격 도구 구분 가능

# [security_log 포맷 예시]
#   192.130.2.30 - [09/Jun/2026:22:15:30 +0900]
#   "POST /login HTTP/1.1" status=401
#   body_bytes=48
#   request_time=0.015
#   xff="192.130.2.30"
#   user_agent="Zekdf/5.0"
log_format security_log
'$remote_addr - [$time_local] '
'"$request" status=$status '
'body_bytes=$body_bytes_sent '
'request_time=$request_time '
'xff="$http_x_forwarded_for" '
'user_agent="$http_user_agent"';


# [security_json 포맷 예시]
# {
#   "time":"2026-06-09T21:15:30+09:00",
#   "remote_addr":"172.31.10.15",
#   "xff":"203.0.113.50",
#   "method":"POST",
#   "uri":"/login",
#   "status":401,
#   "body_bytes":48,
#   "request_time":0.015,
#   "host":"bank.example.com",
#   "user_agent":"Mozilla/5.0"-> Locust 공격시 agent = locust가 됨.
# }
log_format security_json escape=json
'{'
  '"time":"$time_iso8601",'
  '"remote_addr":"$remote_addr",'
  '"xff":"$http_x_forwarded_for",'
  '"method":"$request_method",'
  '"uri":"$request_uri",'
  '"status":$status,'
  '"body_bytes":$body_bytes_sent,'
  '"request_time":$request_time,'
  '"host":"$host",'
  '"user_agent":"$http_user_agent"'
'}';