# security/nginx/rate-limit.conf
# 요청 제한 정책 정의

# $binary_remote_addr : 클라이언트 IP 기준 요청 횟수 측정
# zone: 요청 상태 저장할 공유 메모리 영역
# rate : 허용 요청 수 기준

# 429 Too Many Requests
limit_req_status 429;

# 로그인 API 제한 : brute-force 공격 방어
# IP당 1분에 5회
limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;

# 이체 API 제한 : 민감 금융 기능 남용 방지
# IP당 1분에 3회
limit_req_zone $binary_remote_addr zone=transfer_limit:10m rate=3r/m;

# 일반 API 제한 : API Flooding 완화
# IP당 초당 10회
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;