# project2-security/docker/promtail/promtail-config.yaml
# promtail ec2-Web 용 설정 파일

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_HOST}:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        
        labels:
          job: nginx-access
          server: ${SERVER_NAME}
          __path__: /var/log/nginx/access.log

  - job_name: nginx-error
    
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          server: ${SERVER_NAME}
          __path__: /var/log/nginx/error.log
