 [Definition]

# JSON Nginx Log에서 /login 401 반복 탐지
# {"uri":"/login","status":401,"xff":"203.0.113.50",...}

failregex = ^.*"xff":"<HOST>".*"uri":"\/login".*"status":401.*$
            ^.*"remote_addr":"<HOST>".*"uri":"\/login".*"status":401.*$

ignoreregex =